### PR TITLE
Update runtime to 3.34

### PR DESCRIPTION
**Pull request by LeandroStanger**
Reverts flathub/net.lutris.Lutris#49

### CODE REVIEW

**Comment by gasinvein** [comment]
We'll update the runtime once it's actually ready.

**Comment by A6GibKm** [comment]
To be fair it landed yesterday at flathub.

**Comment by gasinvein** [comment]
@A6GibKm Well then, reopened.

I believe the latest 3.34beta and 3.34 are more or less identical, so it should be safe to merge.

**Comment by p1u3o** [comment]
I gave this a quick test and it seems to work.

However, shouldn't no-autodownload for org.freedesktop.Platform.GL32 be set to false? otherwise, I don't think Flatpak won't automatically pull in the 32bit nvidia driver.

**Comment by gasinvein** [comment]
@p1u3o No, `download-if: active-gl-driver` should handle it and download the extension depending on your GPU. See #34.

**Comment by p1u3o** [comment]
@gasinvein Oh. I think I'm just hitting into the Flatpak bug where uninstall --unused and update uninstalls a bunch of runtimes and then update brings them back.

**Pull request merged**
