### PR TITLE
Add zenity

### PR DESCRIPTION
**Pull request by UsernameRandomlyGenerated**
For issue https://github.com/flathub/net.lutris.Lutris/issues/182

### CODE REVIEW

**Comment by juligreen** [comment]
@UsernameRandomlyGenerated could you try the following?

```
  - name: zenity
    buildsystem: meson
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/zenity.git
        tag: 3.41.0
```

**Comment by A6GibKm** [comment]
> @UsernameRandomlyGenerated could you try the following?
> 
> ```
>   - name: zenity
>     buildsystem: meson
>     sources:
>       - type: git
>         url: https://gitlab.gnome.org/GNOME/zenity.git
>         tag: 3.41.0
> ```

If we are going to use a GNOME source please use the official link https://download.gnome.org/sources/zenity/3.41/zenity-3.41.0.tar.xz.

**Comment by juligreen** [comment]
```
  - name: zenity
    buildsystem: meson
    sources:
      - type: archive
        url: https://download.gnome.org/sources/zenity/3.41/zenity-3.41.0.tar.xz
        sha256: 19b676c3510e22badfcc3204062d432ba537402f5e0ae26128c0d90c954037e1
```

This should work then

@A6GibKm how to you find the project id for x-data-checker?

**Comment by A6GibKm** [comment]
> @A6GibKm how to you find the project id for x-data-checker?

Its just what you see in the url, `zenity` in this case.

**Comment by A6GibKm** [comment]
Could anyone confirm it works?

**Comment by UsernameRandomlyGenerated** [comment]
Installer works fine, doesn't complain about zenity anymore. I can't say about the game itself as it broke recently for me and won't launch (but it's the same with native lutris package).

**Comment by UsernameRandomlyGenerated** [comment]
I've fixed my problem with League not working on Lutris so I repushed it to test flatpak lutris, I'll post results after it builds.

**Comment by juligreen** [comment]
bot, build net.lutris.Lutris

**Comment by A6GibKm** [comment]
Did anyone test that this fixes #182 ?

**Comment by juligreen** [comment]
Yes, this works and can be merged.

**Comment by stacyharper** [comment]
I still got the issue. This merge already is in effect ? Should I do something ?

**Comment by UsernameRandomlyGenerated** [comment]
I don't think the current flatpak available version has that fix yet. I can confirm that lutris installed from this
`flatpak install --user https://dl.flathub.org/build-repo/70907/net.lutris.Lutris.flatpakref`
worked, but it has expired so we'll have to wait (or build from latest source)

**Pull request merged**
