### PR TITLE
Add xterm

### PR DESCRIPTION
**Pull request by juligreen**
This fixes the issue described in https://github.com/flathub/net.lutris.Lutris/issues/141

With this you can use the "Open Bash terminal" and "Run in a terminal" functionality of Lutris.
image

image

I didn't go with the proposed gnome-terminal as it added more than 50 lines of code with all it's dependencies.

### CODE REVIEW

**Comment by A6GibKm** [comment]
@gasinvein Any opinion on this? Since there is no portal for a terminal, it seems sensible to include a terminal, but idk about the choice.

**Comment by gasinvein** [comment]
>it seems sensible to include a terminal

Probably so.

> idk about the choice

Me neither. Maybe there are some lightweight GTK3-based terminals or something.

**Comment by juligreen** [comment]
> Me neither. Maybe there are some lightweight GTK3-based terminals or something.

The issue is that the terminal must be listed in [this list](https://github.com/lutris/lutris/blob/2b7ef5dc01daa9484fd6bf3c5822feb4f3af978c/lutris/util/linux.py#L45) for lutris to discover it (or you'd have to create a PR for lutris to add it there)

As far as I know xterm is pretty lightweight.

**Comment by gasinvein** [comment]
AFAIK xterm doesn't support native Wayland.

**Comment by juligreen** [comment]
Oh that might be right.

Which terminal should I look into adding instead?

**Comment by A6GibKm** [comment]
alacritty and kitty support Wayland. Kitti depends on python (slow start time) so it might be better to use alacritti.

**Pull request closed without merging**
