### PR TITLE
Add xprop and xwininfo, update Gnome runtime to 46

### PR DESCRIPTION
**Pull request by strycore**

### CODE REVIEW

**Comment by strycore** [comment]
bot, build

**Comment by strycore** [comment]
bot, build

**Comment by strycore** [comment]
bot, build

**Comment by strycore** [comment]
bot, build

**Comment by bbhtt** [comment]
The download cache probably got corrupted with the previous failures. Someone needs to drop it.

Probably best for you to switch to a distro source mirror like https://src.fedoraproject.org/lookaside/pkgs/gsm/ or each distro should have their own.

**Comment by strycore** [comment]
> The download cache probably got corrupted with the previous failures. Someone needs to drop it.
> 
> Probably best for you to switch to a distro source mirror like https://src.fedoraproject.org/lookaside/pkgs/gsm/, https://distfiles.alpinelinux.org/distfiles/v3.12/ etc. or each distro should have their own.

Thanks for the tip! I got busy with some other things so it took a while to get back to this issue but I've relaunched a build with the Fedora provided source.

**Comment by strycore** [comment]
bot, build

**Comment by strycore** [comment]
If this fails again, I'm removing the gsm dependency. I don't know what it is or why we have it.

**Comment by strycore** [comment]
I give up.

**Comment by strycore** [comment]
:astonished: :fireworks: :raised_hands: :heart_hands:

**Pull request merged**
