### PR TITLE
Switch to umu rename commit

### PR DESCRIPTION
**Pull request by strycore**

### CODE REVIEW

**Comment by strycore** [comment]
@flathubbot build

**Comment by A6GibKm** [comment]
The bot is a bit congested at the moment :(

**Comment by strycore** [comment]
> The bot is a bit congested at the moment :(

I would say "being DDOSed" more than "congested"

image

**Comment by A6GibKm** [comment]
You didn't see the 40 or so KDE build that happened a few hours ago.

**Comment by strycore** [comment]
> You didn't see the 40 or so KDE build that happened a few hours ago.

There's a few KDE packages at the bottom of the queue. The builds are from bbhtt.zn0i8@slmail.me as well

This user needs to be permanently banned from Flathub asap.

**Comment by A6GibKm** [comment]
There was an incident where all official builds failed for a period of around 8 hours, and they had to be rebuild. this coincided with both GNOME and KDE releases. So the queue got very long.

**Comment by strycore** [comment]
Ah ok, makes more sense! No DDOS then!

**Pull request merged**
