### PR TITLE
Update to GNOME 40 runtime

### PR DESCRIPTION
**Pull request by A6GibKm**
Continuation of #145. Remember to install org.gnome.Platform.Compat.i386//40 for this to work.

### CODE REVIEW

**Comment by A6GibKm** [comment]
@FakeShemp Thanks! The correct version of vulkan tools was missing. I want to merge this as soon as some people test that it works. It works here with overwatch.

**Comment by FakeShemp** [comment]
Awesome! Thanks

**Comment by FakeShemp** [comment]
Works fine as far as I can tell.

**Comment by gasinvein** [comment]
I guess there weren't many impacting changes - Gnome SDK 40 is based on the same FD.o SDK 20.08.

**Pull request merged**
