### PR TITLE
Update all Python dependencies and target Lutris 0.5.11

### PR DESCRIPTION
**Pull request by ntninja**
Includes patch for crash-on-startup bug in that version when the added `pypresence` package is installed on Python 3.9 or below.

### CODE REVIEW

**Comment by strycore** [comment]
i've removed the type hints, your patch is no longer valid.

**Comment by strycore** [comment]
The commit this PR targets is older than the one currently shipped.

**Comment by ntninja** [comment]
> The commit this PR targets is older than the one currently shipped.

It is not, this PR targets Lutris 98a4005a7babe7cc9aae47cb2e453c0978aedde0 aka v0.5.11, while previously this repo targeted 703df306b3bba3ab6ba8fc1400f526999f4ec7f0 aka v0.5.11-beta1 …

(I can also remove the patch file again and target latest master if that is what you prefer…)

**Comment by strycore** [comment]
Ah, I see, the master branch is ahead of the beta branch, this one also targets 98a4005a7babe7cc9aae47cb2e453c0978aedde0.

I'd prefer not have to maintain a collection of patches specifically for Flatpak and have the modifications done directly upstream.
And I've started tolerating type hints in patches since we've recently bumped the supported Python versions but if they are going to cause any problem, I'd rather not have them at all.

**Comment by ntninja** [comment]
Do you want me to reopen targeting latest master, so as to avoid the patch while still updating?

**Pull request closed without merging**
