### PR TITLE
Update runtime to 45

### PR DESCRIPTION
**Pull request by A6GibKm**
I am marking as WIP until I can test it.

### CODE REVIEW

**Comment by strycore** [comment]
Looks like the build is failing with vulkan-tools, maybe this can be temporarily disabled during the migration to runtime 45, it's not absolutely needed by Lutris (although, it would still need to be added back)

**Comment by A6GibKm** [comment]
Tomorrow ill try local builds to speed things out a bit. I prob just have to match the version used by the sdk

**Comment by A6GibKm** [comment]
Poetry and kitty are failing to build.

**Comment by A6GibKm** [comment]
I replaced kitty with blackbox for the moment. Building kitty is beyond me, newer versions use go.

**Comment by A6GibKm** [comment]
Builds done but I just noticed that blackbox is not in the supported terminals (util/linux.py:47).

**Comment by A6GibKm** [comment]
Fixed kitty, but I have to be clear that this is a time bomb and that we are locked to older versions until someone figures how to build newer ones with go.

This is ready for review and testing.

**Comment by strycore** [comment]
> Fixed kitty, but I have to be clear that this is a time bomb 

It doesn't have to be kitty but we need at least one graphical terminal emulator in the flatpak

**Comment by A6GibKm** [comment]
Yeah, we can go back to blackbox, (which is a terminal that works perfectly well sandboxed) in the future, but it will need to be supported by lutris, the binary name is missing in the list of terminals.

**Comment by strycore** [comment]
image

Why is still here?  I thought that was resolved

**Comment by strycore** [comment]
Clicking the GOG login window produces an empty dialog and shows the following errors:

```KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 390x500: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 390x500: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 390x500: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
```

**Comment by A6GibKm** [comment]
> image
> 
> Why is still here? I thought that was resolved

Well, you can only pull dependencies from your same repo and since this is not the flathub repo it wont work.

**Comment by strycore** [comment]
With `WEBKIT_DISABLE_DMABUF_RENDERER=1 flatpak run net.lutris.Lutris` I'm able to get a login window for GOG. 

I still get a lot of warnings on startup and when opening the GOG login:

```
Gtk-Message: 13:41:08.068: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:41:08.110: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:41:08.110: Failed to load module "pk-gtk-module"
Gtk-Message: 13:41:08.110: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:41:08.111: Failed to load module "pk-gtk-module"
```

**Comment by A6GibKm** [comment]
I wonder who is calling those, but at least the canberra one does not mean anything.

**Comment by strycore** [comment]
I think those are modules that most Gtk apps would expect to be present but for some reason are not included in the Gnome runtime.

**Comment by A6GibKm** [comment]
I dont know a single gnome app that uses any of those. I know electron expects Canberra for some reason, but it doesn't do anything really (its for sound themes, but no one uses them).

**Comment by strycore** [comment]
I would provide them nonetheless even if they are not used, just for the sake of not having log polluted by meaningless messages

**Comment by A6GibKm** [comment]
- libcanberra has been [deprecated](https://discourse.gnome.org/t/is-libcanberra-deprecated/10336) for many, many years. I would advice against it, specially since is x11 only. 
- pk-gtk-module is for PackageKit, since we are in a sandbox I feel that would throw even worse errors.
- https://github.com/linuxmint/xapp is the later. 

As far as I know only electron expects the first, and some QT apps might ask for more in the list. 

It took me around 4 hours of nonstop compiling to get this done, adding more modules will make this only harder in the future.

**Comment by strycore** [comment]
I see, maybe it would be easier to suppress those warnings on Gtk's side? 

I know they're not really important and don't affect how the program works but from an end user's perspective, they don't necessarily know that and this kind of message can lead to some confusion while troubleshooting unrelated issues. 

Since this build has a workaround against #364, I'm going to merge it and we can possibly find a way to suppress the warnings in a later patch. For the time being we should also pass WEBKIT_DISABLE_DMABUF_RENDERER=1 by default when running from the Flatpak.

**Comment by strycore** [comment]
Some hints about removing Gtk messages: https://ar.al/2021/10/15/how-to-disable-gtk-message-warnings-in-your-app/

**Comment by A6GibKm** [comment]
Sounds like a reasonable solution. In any case the real fix would be to fix electron or the toolkit that explicitly calls those warnings.

**Comment by strycore** [comment]
I managed to get rid of the xapp one by running `GTK3_MODULES="" flatpak run net.lutris.Lutris`

**Pull request merged**
