### PR TITLE
Release 0.5.12

### PR DESCRIPTION
**Pull request by strycore**

### CODE REVIEW

**Comment by A6GibKm** [comment]
The patch for the lutris module should be removed as the associated PR is already in lutris.

**Comment by A6GibKm** [comment]
dosbox is failing, maybe one could try [0.79.1](https://github.com/dosbox-staging/dosbox-staging/releases/tag/v0.79.1)

**Comment by strycore** [comment]
>  The patch for the lutris module should be removed as the associated PR is already in lutris.

No, I reverted the patch because it broke Lutris on Debian.

**Comment by A6GibKm** [comment]
> No, I reverted the patch because it broke Lutris on Debian.

How? It was using a try statement to prevent that issue.

**Comment by strycore** [comment]
The debian/control file listed a package not available in Debian stable

**Pull request merged**
