### PR TITLE
Update gamemode to 1.6

### PR DESCRIPTION
**Pull request by A6GibKm**
This is untested. I don't have access to a gaming machine so I can't test this at the moment.

### CODE REVIEW

**Comment by A6GibKm** [comment]
I am marking this as draft until someone can confirm that it is indeed working as intended.

**Comment by TheEvilSkeleton** [comment]
How can we tell if GameMode is running or not? I don't really game, but I don't mind testing a bit here and there/

**Comment by A6GibKm** [comment]
I am not entirely sure, but `lutris -d` at least *claims* that it is running if that it is the case.

**Comment by TheEvilSkeleton** [comment]
Sorry for the delay. I was doing my homework. Unfortunately I will have to delay even more because my laptop is at 5%, so I will sleep and will start testing tomorrow.

Hope you  don't mind.

**Comment by TheEvilSkeleton** [comment]
bot, build

**Comment by TheEvilSkeleton** [comment]
Is it supposed to take that long?

**Comment by A6GibKm** [comment]
Yeah, lot of things to build... but no, it should be somewhat faster to build.

**Comment by TheEvilSkeleton** [comment]
Well Minecraft doesn't work. That's a bad start

That's the only game I can play on my laptop because I don't want the fans to start spinning

**Comment by A6GibKm** [comment]
I get the following error, but have in mind that this was using the other PR #116 which uses gamemode 1.5.1 so that might be unrelated.
```
[21:57:33 INFO]: Minecraft Launcher 1.6.89-j (through bootstrap 5) started on linux...
[21:57:33 INFO]: Current time is Sep 29, 2020 9:57:33 PM
[21:57:33 INFO]: System.getProperty('os.name') == 'Linux'
[21:57:33 INFO]: System.getProperty('os.version') == '5.8.11-300.fc33.x86_64'
[21:57:33 INFO]: System.getProperty('os.arch') == 'amd64'
[21:57:33 INFO]: System.getProperty('java.version') == '1.8.0_73'
[21:57:33 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[21:57:33 INFO]: System.getProperty('sun.arch.data.model') == '64'
[21:57:33 INFO]: proxy == DIRECT
[21:57:33 INFO]: JFX is already initialized
Gtk-Message: 21:57:33.373: Failed to load module "canberra-gtk-module"
[21:57:33 INFO]: Refreshing local version list...
[21:57:33 INFO]: Refreshing remote version list...
[21:57:33 INFO]: Refresh complete.
[21:57:33 INFO]: Loaded 1 profile(s); selected 'xxxxx'
[21:57:33 INFO]: Refreshing auth...
[21:57:33 INFO]: Logging in with access token
[21:57:35 INFO]: Getting syncinfo for selected version
[21:57:35 INFO]: Queueing library & version downloads
[21:57:35 FATAL]: Unhandled exception in thread Thread[pool-2-thread-2,5,main]
com.google.gson.JsonSyntaxException: duplicate key: null
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:191) ~[Minecraft.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:146) ~[Minecraft.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[Minecraft.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[Minecraft.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:795) ~[Minecraft.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:761) ~[Minecraft.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:710) ~[Minecraft.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:682) ~[Minecraft.jar:?]
	at net.minecraft.launcher.updater.RemoteVersionList.getCompleteVersion(RemoteVersionList.java:32) ~[launcher.jar:1.6.89-j]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getLatestCompleteVersion(MinecraftVersionManager.java:213) ~[launcher.jar:1.6.89-j]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getLatestCompleteVersion(MinecraftVersionManager.java:37) ~[launcher.jar:1.6.89-j]
	at com.mojang.launcher.game.runner.AbstractGameRunner.playGame(AbstractGameRunner.java:67) ~[launcher.jar:1.6.89-j]
	at net.minecraft.launcher.game.GameLaunchDispatcher$1.run(GameLaunchDispatcher.java:111) ~[launcher.jar:1.6.89-j]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
[21:57:45 INFO]: Window closed, shutting down.
[21:57:45 INFO]: Halting executors
[21:57:45 INFO]: Awaiting termination.
[21:57:45 INFO]: Goodbye.
dbus[162]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file ../../dbus/dbus-pending-call.c line 765.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Game is considered exited.
Initial process has exited.
All children have exited.
Exit with returncode 134
```

**Comment by A6GibKm** [comment]
Note that it is not working for me either on the beta branch of lutris.

**Comment by A6GibKm** [comment]
This seems to be working fine

**Pull request merged**
