### PR TITLE
Update to v0.5.5

### LINKED ISSUE #97: Crash at startup
```
2020-03-30 13:42:13,273: Package 'distro' unavailable. Unable to read Linux distribution
Traceback (most recent call last):
  File "/app/bin/lutris", line 34, in <module>
    from lutris.gui.application import Application
  File "/app/lib/python3.7/site-packages/lutris/gui/application.py", line 35, in <module>
    from lutris.game import Game
  File "/app/lib/python3.7/site-packages/lutris/game.py", line 14, in <module>
    from lutris.runners import import_runner, InvalidRunner, wine
  File "/app/lib/python3.7/site-packages/lutris/runners/wine.py", line 11, in <module>
    from lutris.runners.runner import Runner
  File "/app/lib/python3.7/site-packages/lutris/runners/runner.py", line 7, in <module>
    from lutris.config import LutrisConfig
  File "/app/lib/python3.7/site-packages/lutris/config.py", line 6, in <module>
    from lutris import settings, sysoptions
  File "/app/lib/python3.7/site-packages/lutris/sysoptions.py", line 9, in <module>
    from lutris.util.display import USE_DRI_PRIME, DISPLAY_MANAGER
  File "/app/lib/python3.7/site-packages/lutris/util/display.py", line 4, in <module>
    from dbus.exceptions import DBusException
ModuleNotFoundError: No module named 'dbus'
```

### PR DESCRIPTION
**Pull request by p1u3o**
This adds a couple of dependencies. 

Closes #97 

Proof it starts, was able to also run my Battle.net install as normal.
Screenshot from 2020-03-30 14-38-18

### CODE REVIEW

**Comment by LeandroStanger** [comment]
Thanks!

**Comment by Khyber3737** [comment]
A little worrying how lightly adding random external dependencies is taken but I guess that's how open source works. I didn't realized until this PR that Lutris is one of the worst offenders. Oh well.

**Comment by p1u3o** [comment]
> A little worrying how lightly adding random external dependencies is taken but I guess that's how open source works. I didn't realized until this PR that Lutris is one of the worst offenders. Oh well.

¯\_(ツ)_/¯

I'd say we're somewhat lucky in that the Flatpak is sandboxed, but looking at the manifest we're giving a large amount of permissions anyway.

**Comment by gasinvein** [comment]
@p1u3o 
>we're somewhat lucky in that the Flatpak is sandboxed

Just pay attention to updates, something like f850c202af1818794619063c4e4e351a7acd06c0 could happen again.

**Comment by p1u3o** [comment]
> Just pay attention to updates, something like [f850c20](https://github.com/flathub/net.lutris.Lutris/commit/f850c202af1818794619063c4e4e351a7acd06c0) could happen again.

Why does the manifest need xdg-music?

**Comment by gasinvein** [comment]
> Why does the manifest need xdg-music?

Wine maps windows user folders to some of XDG directories, including xdg-music. If a directory isn't available, it'll be mapped to home, and home in sandbox is on tmpfs. So if some wine app saves some file there - it'll be lost after restart.

**Pull request merged**
