### PR TITLE
Add java 8 for minecraft launchers etc.

### PR DESCRIPTION
**Pull request by nickavem**
I and [others](https://github.com/flathub/net.lutris.Lutris/issues/147) would appreciate if java were included in the application for Minecraft and Minecraft launchers.

### CODE REVIEW

**Comment by nickavem** [comment]
Build works fine and can run both vanilla and modded Minecraft very well.

**Comment by nickavem** [comment]
For anyone interested, if this doesn't get pushed I may try building GDLauncher as a flatpak. MultiMC was a disaster, and ATLauncher is already so portable it doesn't make too much sense as a flatpak, but GDLauncher might be the sweet spot.

**Comment by tommytran732** [comment]
Seems like it is gonna awhile for someone to merge it... In the meantime, I wonder if there is a way to make it default to the latest default openjdk version? I get that 8 is the most compatible one, but it is quite old at this point. I think just letting the openjdk sdk be the latest would be better.

**Comment by nickavem** [comment]
The Cost/Benefit there would be questionable. Not even Fedora or Ubuntu use the latest java version. I believe the Minecraft flatpak has some way of managing dual versions that I could look into... Anything higher than 11 just wouldn't make sense for Minecraft, though.

**Comment by nickavem** [comment]
@A6GibKm Could you take a look at this?

**Comment by A6GibKm** [comment]
Sorry for not replying earlier. The issue here is that we cannot bundle every single dependency for every single launcher/game, specially when minecraft is already available in flatpak.

I do see an use case for people who want to mod it, which is very problematic with the already existing flatpak.

**Comment by A6GibKm** [comment]
I would highly encourage you to do a Flatpaks for any of those alternatives you mention, while I don't know what flathub admins would make of this, I know many people who had the need for them in the past.

> ATLauncher is already so portable it doesn't make too much sense as a flatpak 

Many apps claim they are, but more often than not it is not the case and a flatpak is always welcome. There are many reasons to use a flatpak, being easy to install is only one of them.

**Comment by nickavem** [comment]
Sigh... fair enough.

I will try ATLauncher again as I have used it forever and really do love it but if that doesn't work out maybe GDLauncher will. Either way I'll report back.

**Comment by nickavem** [comment]
Well, I got a build going, but upstream doesn't seem very interested. I'll try and convince them, but I want to avoid publishing without their consent.

**Comment by A6GibKm** [comment]
I think that if you manage to make this a Flatpak extension for the already existing Minecraft, you could convince the admins, but I dont know how would that work to be honest, I have zero experience on these launchers.

**Comment by tommytran732** [comment]
> Sigh... fair enough.
> 
> I will try ATLauncher again as I have used it forever and really do love it but if that doesn't work out maybe GDLauncher will. Either way I'll report back.

As far as I remember, ATLauncher was on Flathub but it got removed due to it promoting piracy? https://github.com/flathub/org.tlauncher.TLauncher/issues/9#event-4006809390



> Sorry for not replying earlier. The issue here is that we cannot bundle every single dependency for every single launcher/game, specially when minecraft is already available in flatpak.
> 
> I do see an use case for people who want to mod it, which is very problematic with the already existing flatpak.

The problem is, the flatpak Minecraft is outdated and it seems like there is a bug that Mojang needs to fix first before the maintainer could update the package: https://github.com/flathub/com.mojang.Minecraft/pull/78

Besides, it would be nice if we could just have Lutris as the launcher for as many apps as possible... it helps organize stuff better. And while yes, it may not be the best idea to bundle every dependency for every single game, Minecraft is really popular and having Java preinstalled will make things much easier for everyone. I hope you would reconsider and merge this pull request.

**Comment by nickavem** [comment]
That is TLauncher, a proprietary mess of a program that deserved to get removed.

ATLauncher is fully open source and requires a Minecraft account to work properly.

**Comment by strycore** [comment]
> Sorry for not replying earlier. The issue here is that we cannot bundle every single dependency for every single launcher/game, specially when minecraft is already available in flatpak.

No. We *WIIL* bundle *EVERYTHING* needed to make *EVERY* game work. 
I'm not validating this flatpak until it has the EXACT SAME FEATURE SET as the native version.

**Comment by A6GibKm** [comment]
>  I'm not validating this flatpak until it has the EXACT SAME FEATURE SET as the native version.

The reason I am not willing to bundle everything is that I don't have the time and knowledge to maintain this gigantic set of dependencies by myself. Of course, with some help I can happily change that decision.

**Comment by strycore** [comment]
I can help with that, it's not a problem

**Pull request closed without merging**
