### PR TITLE
Update runtime to 3.38beta

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build

**Comment by LeandroStanger** [comment]
bot, build

**Comment by LeandroStanger** [comment]
bot, build

**Comment by A6GibKm** [comment]
While it is not the issue at hand here, to build p7zip with gcc10 you need to add a patch, see https://github.com/flathub/org.gnome.FileRoller/pull/2/files.

**Comment by A6GibKm** [comment]
This will also probably need to update `gnome-desktop`, use the version at https://download.gnome.org/sources/gnome-desktop/3.37/ until a 3.38 gets released.

**Pull request closed without merging**
