### PR TITLE
Bump to v0.5.3

### LINKED ISSUE #43: Update to v0.5.3
https://github.com/lutris/lutris/releases/tag/v0.5.3

### PR DESCRIPTION
**Pull request by A6GibKm**
- Removed patches/lutris-appdata-tags-pr2134.patch
- Removed patches/lutris-flatpak-support-pr2106.patch
- Renamed patches/lutris-libgamemodeauto-path.patch to indicate its pr

Lutris is opening fine.
I cannot properly test this with a game because of #41. #42 does not fix it for some reason. 

Fixes #43

### CODE REVIEW

**Comment by A6GibKm** [comment]
#43

**Comment by RobLoach** [comment]
Unsure if it's related or not, but I'm getting a few errors when trying to run Xonotic...

```
GameMode ERROR: Could not call method 'UnregisterGame' on 'org.freedesktop.portal.Desktop': No such interface 'org.freedesktop.portal.GameMode' on object at path /org/freedesktop/portal/desktop
gamemodeauto: Could not call method 'UnregisterGame' on 'org.freedesktop.portal.Desktop': No such interface 'org.freedesktop.portal.GameMode' on object at path /org/freedesktop/portal/desktop
Waiting on children
Exit with returncode 1
GameMode ERROR: Could not call method 'UnregisterGame' on 'org.freedesktop.portal.Desktop': No such interface 'org.freedesktop.portal.GameMode' on object at path /org/freedesktop/portal/desktop
gamemodeauto: Could not call method 'UnregisterGame' on 'org.freedesktop.portal.Desktop': No such interface 'org.freedesktop.portal.GameMode' on object at path /org/freedesktop/portal/desktop
2019-09-07 22:44:00,734: Game still running (state: running)
2019-09-07 22:44:00,735: Stopping Xonotic (linux)
```

**Comment by A6GibKm** [comment]
I tested this in a build without 6445c9eed9f2a353472093bcd7df62526afb456b and it is working.

**Comment by gasinvein** [comment]
@RobLoach It's not, seem like you don't have GameMode installed.

**Comment by gasinvein** [comment]
Looks like this actualizes work on #19

**Comment by A6GibKm** [comment]
Like this @gasinvein ? How does this helps with #19?

**Comment by gasinvein** [comment]
@A6GibKm #19 is unrelated to the patch. Lutris 0.5.3. announced Discord RP support, so we probably would want to add it.

**Comment by A6GibKm** [comment]
I am currently testing that feature, should I use pypresence 3.1.0 or commit https://github.com/qwertyquerty/pypresence/pull/71/commits/a397e6395ade0688c76c33fc27b31671d663db84, since the files are fundamentally different using your patch fails.

**Comment by gasinvein** [comment]
@A6GibKm I'll open a new PR with Discord-RP once this one is tested and merged.

**Comment by A6GibKm** [comment]
Sounds fine, I was about to suggest the same as 
1. I am having problems testing on the gnome-sdk and I have to build everything twice
2. It involves more involved changes, see https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)

**Comment by A6GibKm** [comment]
Gnome runtime got an update, still can't run this due to #41.

**Comment by Saroufim** [comment]
Yup. Can confirm. I'm still getting
```
 bwrap: Can't mkdir /app/lib/i386-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256
```

**Comment by gasinvein** [comment]
@abderrahim, excuse me CC'ing  you again, is the latest Gnome SDK update expected to include the GL dir fix?

**Comment by abderrahim** [comment]
It was supposed to, but it indeed doesn't. Should be fixed by https://gitlab.gnome.org/GNOME/gnome-build-meta/merge_requests/372

**Comment by gasinvein** [comment]
@abderrahim It is fixed now, thanks again.

**Pull request merged**
