### PR TITLE
Update runtime to 43

### PR DESCRIPTION
**Pull request by A6GibKm**

### CODE REVIEW

**Comment by A6GibKm** [comment]
I haven't yet done a local build. Ill post when it is tested.

**Comment by A6GibKm** [comment]
Blocked on https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/issues/27, see the related MR https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/pull/26.

**Comment by A6GibKm** [comment]
bot, build

**Comment by A6GibKm** [comment]
Ok, this is not going to work,

```
File "/app/lib/python3.10/site-packages/lutris/gui/dialogs/webconnect_dialog.py", line 6, in <module>
    gi.require_version("WebKit2", "4.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
```

**Comment by A6GibKm** [comment]
Ok, with the patch it works. @strycore does this look ok?

**Comment by strycore** [comment]
Looks fine but I'm not going to merge it into master. Target the beta branch.

**Comment by A6GibKm** [comment]
Done

**Comment by A6GibKm** [comment]
Done.

**Comment by Mershl** [comment]
I've been running the beta for the last week with a vast library without any visible regressions. +1 ready for stable from me.

**Comment by strycore** [comment]
The installation of Ubisoft Connect is broken on the Lutris Flatpak beta. We won't release the new version until this is fixed.

**Comment by A6GibKm** [comment]
Fair, but would it be possible to test if thats related to the runtime update?

**Comment by strycore** [comment]
that would require a build with the current code and the previous runtime to see if the error persists

**Comment by Mershl** [comment]
https://github.com/lutris/lutris/releases/tag/v0.5.12 just got released mentioning a fix of the Ubisoft Connect login. Does this fix the current blocker?

**Pull request merged**
