### PR TITLE
Add Discord-RP support

### LINKED ISSUE #19: Add Discord support

### PR DESCRIPTION
**Pull request by gasinvein**
Depends on #44, fixes #19

Problem here is that discord-rp server (i.e. the Discord app) assumes that client's PID can't be less than 10, which is not the case for flatpak. This problem already [popped up](https://github.com/flathub/com.googleplaymusicdesktopplayer.GPMDP/issues/7#issuecomment-445984660) before.
```
Child "pid" fails because "pid" must be larger than or equal to 10
```

### CODE REVIEW

**Comment by gasinvein** [comment]
Oh great, here we go again
```
Child "pid" fails because "pid" must be larger than or equal to 10
```

**Comment by A6GibKm** [comment]
Is possible to just give a +10 to all the PIDS generated by lutris?

**Comment by gasinvein** [comment]
I see two possible ways to do this, both a hackish and ugly:
* Run a bunch of stub processes (e.g. `/bin/true`) on startup to increase PIDs for next processes spawned by Lutris
* Patch pyprecense to fake PID if real one is less than 10, e.g. send `pid = real_pid + 10`. Shifted PIDs from a namespace don't make sense for Discord anyway

**Comment by gasinvein** [comment]
Also we can just ignore this and blame Discord. 3rd or 4th game launched should naturally have "correct" PID.

**Comment by RobLoach** [comment]
This is great! I tested this in two scenarios....

### Lutris Flatpak with Discord Flatpak

Was able to run Lutris and run Xonotic, but Discord didn't see Game Activity...

Screenshot at 2019-09-14 23-53-29

### Lutris Flatpak with Discord Native

Was able to run Lutris and play Xonotic, and Discord saw the Game Activity...

d


... so it seems that while this works when Discord is run natively, the game activity is not found on Discord when running both through Flatpak. This is likely a problem with the Discord Flatpak rather than this change.

**Comment by gasinvein** [comment]
That's strange, it's intended to work only with flatpak'ed Discord.
Can you run a shell within Lutris sandbox and check if the Discord RP socket appears under `$XDG_RUNTIME_DIR/app/com.discordapp.Discord/`?

**Comment by A6GibKm** [comment]
Can confirm, it isn't working. The dowload link is down, I had to port everything from the beta branch to test.
```
[📦 net.lutris.Lutris ~]$ cd $XDG_RUNTIME_DIR/app/com.discordapp.Discord/
[📦 net.lutris.Lutris com.discordapp.Discord]$ ls
discord-ipc-0
```

**Pull request closed without merging**
